INSERT INTO T_DEPARTMENT(PK,DEPARTMENT_NAME) VALUES(100,'İnsan Kaynakları Departmanı');
INSERT INTO T_DEPARTMENT(PK,DEPARTMENT_NAME) VALUES(105,'Bi̇li̇şi̇m Teknoloji̇leri̇ Departmanı');
INSERT INTO T_DEPARTMENT(PK,DEPARTMENT_NAME) VALUES(110,'Muhasebe Departmanı');

INSERT INTO T_UNIT(PK,UNIT_NAME,DEPARTMENT_FK) VALUES(1000,'Yazılım Bi̇ri̇mi̇',100);
INSERT INTO T_UNIT(PK,UNIT_NAME,DEPARTMENT_FK) VALUES(1050,'Network Bi̇ri̇mi̇',100);
INSERT INTO T_UNIT(PK,UNIT_NAME,DEPARTMENT_FK) VALUES(1100,'İşe Alım Bi̇ri̇mi̇',105);
INSERT INTO T_UNIT(PK,UNIT_NAME,DEPARTMENT_FK) VALUES(1150,'Performans Değerlendi̇rme Bi̇ri̇mi̇',105);
INSERT INTO T_UNIT(PK,UNIT_NAME,DEPARTMENT_FK) VALUES(1200,'Geli̇r-gi̇der Bi̇ri̇mi̇',110);
INSERT INTO T_UNIT(PK,UNIT_NAME,DEPARTMENT_FK) VALUES(1250,'Bütçe Raporlama Bi̇ri̇mi̇',110);
INSERT INTO T_UNIT(PK,UNIT_NAME,DEPARTMENT_FK) VALUES(1300,'İş Zekası Bi̇ri̇mi̇',105);

INSERT INTO T_ROLE(PK,ROLE_NAME) VALUES(10000,'Genel Müdür');
INSERT INTO T_ROLE(PK,ROLE_NAME) VALUES(10500,'Müdür');
INSERT INTO T_ROLE(PK,ROLE_NAME) VALUES(11000,'Yöneti̇ci̇');
INSERT INTO T_ROLE(PK,ROLE_NAME) VALUES(11500,'Yazılımcı');
INSERT INTO T_ROLE(PK,ROLE_NAME) VALUES(16000,'Muhasebeci̇');
INSERT INTO T_ROLE(PK,ROLE_NAME) VALUES(12000,'Yazılım Uzmanı');
INSERT INTO T_ROLE(PK,ROLE_NAME) VALUES(12500,'Anali̇st');
INSERT INTO T_ROLE(PK,ROLE_NAME) VALUES(13000,'Anali̇z Uzmanı');
INSERT INTO T_ROLE(PK,ROLE_NAME) VALUES(13500,'Bütçeci̇');
INSERT INTO T_ROLE(PK,ROLE_NAME) VALUES(14000,'Veri̇ Tabanı Uzmanı');
INSERT INTO T_ROLE(PK,ROLE_NAME) VALUES(14500,'Si̇stem Yöneti̇ci̇si̇');
INSERT INTO T_ROLE(PK,ROLE_NAME) VALUES(15000,'Tasarımcı');
INSERT INTO T_ROLE(PK,ROLE_NAME) VALUES(15500,'Network Uzmanı');

INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(1,'Java');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(2,'Javascript');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(3,'PHP');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(4,'HTML');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(5,'CSS');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(6,'AJAX');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(7,'C#');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(8,'C++');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(9,'C');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(10,'ASP.NET');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(11,'.NET');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(12,'Python');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(13,'Ruby');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(14,'XML');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(15,'Objective-C');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(16,'Android');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(17,'IOS');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(18,'Node.js');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(19,'Angular.js');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(20,'Oracle');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(21,'SQL');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(22,'MYSQL');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(23,'PL/SQL');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(24,'MS Excel');
INSERT INTO T_ABILITY(PK,ABILITY_NAME) VALUES(25,'MS Word');

INSERT INTO T_LOUNGE(PK,LOUNGE_NAME) VALUES(1,'Salon 1');
INSERT INTO T_LOUNGE(PK,LOUNGE_NAME) VALUES(2,'Salon 2');
INSERT INTO T_LOUNGE(PK,LOUNGE_NAME) VALUES(3,'Salon 3');
INSERT INTO T_LOUNGE(PK,LOUNGE_NAME) VALUES(4,'Salon 4');
INSERT INTO T_LOUNGE(PK,LOUNGE_NAME) VALUES(5,'Salon 5');

INSERT INTO T_STATE(PK,STATE_NAME,STATE_ORDER,ALLOW_TO_CHANGE_DETAILS,ALLOW_TO_START,ALLOW_TO_ACTIVITE,ALLOW_TO_CANCEL,ALLOW_TO_TERMINATE,ALLOW_TO_CHANGE_USER_OR_ABLYT) VALUES(1,'AKTİFLEŞTİRİLDİ','1','1','1','0','1','0','1');
INSERT INTO T_STATE(PK,STATE_NAME,STATE_ORDER,ALLOW_TO_CHANGE_DETAILS,ALLOW_TO_START,ALLOW_TO_ACTIVITE,ALLOW_TO_CANCEL,ALLOW_TO_TERMINATE,ALLOW_TO_CHANGE_USER_OR_ABLYT) VALUES(2,'BAŞLADI',2,'0','0','0','0','1','0');
INSERT INTO T_STATE(PK,STATE_NAME,STATE_ORDER,ALLOW_TO_CHANGE_DETAILS,ALLOW_TO_START,ALLOW_TO_ACTIVITE,ALLOW_TO_CANCEL,ALLOW_TO_TERMINATE,ALLOW_TO_CHANGE_USER_OR_ABLYT) VALUES(3,'SONA ERDİ',3,'0','0','0','0','0','0');
INSERT INTO T_STATE(PK,STATE_NAME,STATE_ORDER,ALLOW_TO_CHANGE_DETAILS,ALLOW_TO_START,ALLOW_TO_ACTIVITE,ALLOW_TO_CANCEL,ALLOW_TO_TERMINATE,ALLOW_TO_CHANGE_USER_OR_ABLYT) VALUES(4,'İPTAL EDİLDİ',4,'0','0','1','0','0','0');

INSERT INTO T_ABILITY_LEVEL(PK,LEVEL_NAME,LEVEL_ORDER) VALUES(1,'Çok İyi',1);
INSERT INTO T_ABILITY_LEVEL(PK,LEVEL_NAME,LEVEL_ORDER) VALUES(2,'İyi',2);
INSERT INTO T_ABILITY_LEVEL(PK,LEVEL_NAME,LEVEL_ORDER) VALUES(3,'Orta',3);
INSERT INTO T_ABILITY_LEVEL(PK,LEVEL_NAME,LEVEL_ORDER) VALUES(4,'Kötü',4);
INSERT INTO T_ABILITY_LEVEL(PK,LEVEL_NAME,LEVEL_ORDER) VALUES(5,'Çok Kötü',5);
