CREATE TABLE T_DEPARTMENT(
    PK NUMERIC(1),
    DEPARTMENT_NO NUMERIC(10) NOT NULL,
    DEPARTMENT_NAME VARCHAR(40) NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_TIME TIMESTAMP,
    PRIMARY KEY(PK),
    UNIQUE(DEPARTMENT_NO),
    UNIQUE(DEPARTMENT_NAME)
)

CREATE TABLE T_UNIT(
    PK NUMERIC(2),
    UNIT_NO NUMERIC(10) NOT NULL,
    UNIT_NAME VARCHAR(40) NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    DEPARTMENT_FK NUMERIC(1) NOT NULL,
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_TIME TIMESTAMP,
    PRIMARY KEY(PK),
    FOREIGN KEY(DEPARTMENT_FK) REFERENCES T_DEPARTMENT(PK) ON DELETE CASCADE,
    UNIQUE(UNIT_NO),
    UNIQUE(UNIT_NAME)
)

CREATE TABLE T_ROLE(
    PK NUMERIC(3),
    ROLE_NO NUMERIC(10) NOT NULL,
    ROLE_NAME VARCHAR(40) NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    UNIT_FK NUMERIC(1) NOT NULL,
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_TIME TIMESTAMP,
    PRIMARY KEY(PK),
    FOREIGN KEY(UNIT_FK) REFERENCES T_UNIT(PK) ON DELETE CASCADE,
    UNIQUE(ROLE_NO),
    UNIQUE(ROLE_NAME)
)

CREATE TABLE T_USER(
    PK NUMERIC(5),
    U_ID VARCHAR(20) NOT NULL,
    U_PW VARCHAR(40) NOT NULL,
    FIRST_NAME VARCHAR(40) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    REGISTER_NO NUMERIC(10) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    PHONE_NUMBER VARCHAR(11) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_TIME TIMESTAMP,
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    ROLE_FK NUMERIC(3) NOT NULL,
    PRIMARY KEY(PK),
    UNIQUE(U_ID),
    UNIQUE(REGISTER_NO),
    UNIQUE(PHONE_NUMBER),
    FOREIGN KEY(ROLE_FK) REFERENCES T_ROLE(PK) ON DELETE CASCADE
)

DROP TABLE T_USER

CREATE TABLE T_ABILITY(
    PK NUMERIC(4),
    ABILITY_NAME VARCHAR(40) NOT NULL,
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_TIME TIMESTAMP,
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    PRIMARY KEY(PK),
    UNIQUE(ABILITY_NAME)
)

CREATE TABLE T_ABILITY_LEVEL(
    PK NUMERIC(1),
    LEVEL_NAME VARCHAR(40),
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_TIME TIMESTAMP,
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    PRIMARY KEY(PK),
    UNIQUE(LEVEL_NAME)
)

CREATE TABLE T_USER_ABILITY_REL(
    PK NUMERIC(9),
    USER_FK NUMERIC(5),
    ABILITY_FK NUMERIC(4),
    ABILITY_LEVEL_FK NUMERIC(1),
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_TIME TIMESTAMP,
    PRIMARY KEY(PK),
    FOREIGN KEY(USER_FK) REFERENCES T_USER(PK) ON DELETE CASCADE,
    FOREIGN KEY(ABILITY_FK) REFERENCES T_ABILITY(PK) ON DELETE CASCADE,
    FOREIGN KEY(ABILITY_LEVEL_FK) REFERENCES T_ABILITY_LEVEL(PK) ON DELETE CASCADE
)

CREATE TABLE T_EDUCATION(
    PK NUMERIC(2),
    EDUCATION_SUBJECT VARCHAR(100),
    EDUCATION_CONTENT VARCHAR(1000),
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_TIME TIMESTAMP,   
    PRIMARY KEY(PK) 
)

DROP TABLE T_EDUCATION

CREATE TABLE T_EDUCATION_ABILITY_REL(
    PK NUMERIC(5),
    EDUCATION_FK NUMERIC(2) NOT NULL,
    ABILITY_FK NUMERIC(4) NOT NULL,
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_TIME TIMESTAMP,
    PRIMARY KEY(PK),
    FOREIGN KEY(EDUCATION_FK) REFERENCES T_EDUCATION(PK) ON DELETE CASCADE,
    FOREIGN KEY(ABILITY_FK) REFERENCES T_ABILITY(PK) ON DELETE CASCADE  
)

DROP TABLE T_EDUCATION_ABILITY_REL

CREATE TABLE T_EDUCATION_USER_REL(
    PK NUMERIC(7),
    EDUCATION_FK NUMERIC(2),
    USER_FK NUMERIC(5),
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_TIME TIMESTAMP,
    PRIMARY KEY(PK),
    FOREIGN KEY(EDUCATION_FK) REFERENCES T_EDUCATION(PK) ON DELETE CASCADE,
    FOREIGN KEY(USER_FK) REFERENCES T_USER(PK) ON DELETE CASCADE
)

